namespace SEDiscordBridge
{
    public enum DamageType
    {
        Unknown,
        Explosion,
        Rocket,
        Bullet,
        Mine,
        Environment,
        Drill,
        Radioactivity,
        Deformation,
        Suicide,
        Fall,
        Weapon,
        Fire,
        Squeez,
        Grind,
        Weld,
        Asphyxia,
        LowPressure,
        Bolt,
        Destruction,
        Debug,
        Wolf,
        Spider,
        Temperature,
        Laser
    }
}